#!/bin/bash
# Headrush Block Renamer - Community Edition


echo "---Start renaming Headrush Blocks---"

# Function to rename files based on old prefix and new name
rename_file() {
    local folder="$1"
    local old_prefix="$2"
    local new_name="$3"
    
    # Verify if the folder exists
    if [ -d "$folder" ]; then
        # Search for .block files that start with the specific prefix (case insensitive)
        find "$folder" -maxdepth 1 -iname "${old_prefix}*" -name "*.block" | while read -r file; do
            mv "$file" "$folder/${new_name}.block"
            echo -e "\033[0;32m[OK]\033[0m Folder '$folder': '$(basename "$file")' -> '${new_name}.block'"
        done
    fi
}

# --- 1. PROCESSING: Amp (Headrush Standard) ---
echo "Processing folder: Amp..."
D="Amp"
rename_file "$D" "+05 Tangerine 30 Ch1" "Orange AD30HTC (Clean)"
rename_file "$D" "+05 Tangerine 30 Ch2" "Orange AD30HTC (Drive)"
rename_file "$D" "+11 EPB II Clean" "ENGL Powerball II (Channel 1)"
rename_file "$D" "+11 EPB II Crunch" "ENGL Powerball II (Channel 2)"
rename_file "$D" "+11 EPB II Hi-Lead" "ENGL Powerball II (Channel 4)"
rename_file "$D" "+11 EPB II Lo-Lead" "ENGL Powerball II (Channel 3)"
rename_file "$D" "+17 Trace Elliot Elf" "Trace Elliot ELF"
rename_file "$D" "+59 Deluxe Gain Mod" "Fender Tweed Deluxe (Gain Mod)"
rename_file "$D" "+59 Tweed Bass" "Fender '59 Bassman"
rename_file "$D" "+59 Tweed Deluxe" "Fender Tweed Deluxe"
rename_file "$D" "+59 Tweed Prince" "Fender '59 Princeton"
rename_file "$D" "+64 Black Lux Norm" "Fender Deluxe Reverb (Normal)"
rename_file "$D" "+64 Black Lux Vib" "Fender Deluxe Reverb (Vibrato)"
rename_file "$D" "+64 Black Vib" "Fender Vibroverb"
rename_file "$D" "+65 Black Mini" "Fender Champ 6w"
rename_file "$D" "+65 Black Prince Rev" "Fender Princeton Reverb"
rename_file "$D" "+65 Black Prince" "Fender Princeton"
rename_file "$D" "+65 Black SR" "Fender Super Reverb Blackface"
rename_file "$D" "+65 J45" "Marshall JTM45"
rename_file "$D" "+66 AC Hi Boost Mod" "Vox AC30 Top Boost (Mod)"
rename_file "$D" "+66 AC Hi Boost" "Vox AC30 Top Boost"
rename_file "$D" "+66 Flip Bass" "Ampeg Portaflex B15-N"
rename_file "$D" "+67 Black Duo" "Fender Twin Reverb Blackface"
rename_file "$D" "+67 Black Shimmer" "Fender Dual Showman"
rename_file "$D" "+67 Plexiglas Vari" "Marshall Super Lead Plexi (Variac Mod)"
rename_file "$D" "+68 Plexi EL84 Mod" "Marshall Super Lead Plexi (EL34 tubes mod)"
rename_file "$D" "+68 Plexiglas 50W" "Marshall Super Lead Plexi 50W"
rename_file "$D" "+69 Blue Line Bass" "Ampeg SVT 300w"
rename_file "$D" "+69 Blue Line Scoop" "Ampeg SVT 300w (Scooped)"
rename_file "$D" "+69 Plexiglas 100W" "Marshall Super Lead Plexi 100W"
rename_file "$D" "+82 Lead 800 100W" "Marshall JCM800 (Normal)"
rename_file "$D" "+82 Lead 800 50W" "Marshall JCM800 50w"
rename_file "$D" "+82 Lead 800 Bass Mod" "Marshall JCM800 (Bass Mod)"
rename_file "$D" "+82 Lead 800 Bright" "Marshall JCM800 (Bright)"
rename_file "$D" "+82 Lead 800 TS Mod" "Marshall JCM800 (TS Mod)"
rename_file "$D" "+83 400R" "Gallien-Krueger 800RB"
rename_file "$D" "+84 J-120H" "Roland Jazz Chorus 120 (Head)"
rename_file "$D" "+85 M-2 Lead Cap Mod" "Mesa-Boogie Mark IIc+ (Coupling Cap Mod)"
rename_file "$D" "+85 M-2 Lead" "Mesa-Boogie Mark IIc+ (Drive)"
rename_file "$D" "+89 SL-100 Clean" "Soldano SLO-100 (Clean)"
rename_file "$D" "+89 SL-100 Crunch" "Soldano SLO-100 (Crunch)"
rename_file "$D" "+89 SL-100 Drive" "Soldano SLO-100 (Drive)"
rename_file "$D" "+89 SL-100 Ext Range" "Soldano SLO-100 (Extreme)"
rename_file "$D" "+92 Treadplate Modern" "Mesa Boogie Dual Rectifier (Modern)"
rename_file "$D" "+92 Treadplate Raw" "Mesa Boogie Dual Rectifier (Raw)"
rename_file "$D" "+92 Treadplate Vintage" "Mesa Boogie Dual Rectifier (Vintage)"
rename_file "$D" "+93 MS-30" "Matchless DC30"
rename_file "$D" "+97 RB-01B Blue" "Bogner Ecstasy 101B (Blue Channel)"
rename_file "$D" "+97 RB-01B Green" "Bogner Ecstasy 101B (Green Channel)"
rename_file "$D" "+97 RB-01B Red" "Bogner Ecstasy 101B (Red Channel)"
rename_file "$D" "+99 PV51 II Clean" "Peavey 5150 II (Clean)"
rename_file "$D" "+99 PV51 II Crunch" "Peavey 5150 II (Crunch)"
rename_file "$D" "+99 PV51 II Lead" "Peavey 5150 II (Lead)"

# --- 2. PROCESSING: Cab (Headrush Standard) ---
echo "Processing folder: Cab..."
D="Cab"
rename_file "$D" "+1x12 Black Panel Lux" "1x12 Fender Deluxe Reverb Blackface (Jensen P12N)"
rename_file "$D" "+1x12 Tweed Lux" "1x12 Fender Tweed Deluxe (Jensen P12Q)"
rename_file "$D" "+1x15 Open Back" "1x15 Fender Pro (Jensen P15N)"
rename_file "$D" "+1x8 Custom" "1x8 Fender Champ"
rename_file "$D" "+2x12 AC Blue" "2x12 Vox AC30 (Celestion Alnico Blue)"
rename_file "$D" "+2x12 B30" "2x12 Bogner (Celestion V30)"
rename_file "$D" "+2x12 Black Panel Duo" "2x12 Fender Twin Reverb Blackface (Jensen C12N)"
rename_file "$D" "+2x12 Silver Cone" "2x12 Roland JC-120"
rename_file "$D" "+4x10 Black SR" "4x10 Fender Super Reverb Blackface (Jensen P10R)"
rename_file "$D" "+4x10 Tweed Bass" "4x10 Fender 59 Bassman (Jensen P10Q)"
rename_file "$D" "+4x12 65W" "4x12 Marshall 1960A (Celestion G12-65)"
rename_file "$D" "+4x12 Classic 30W" "4x12 Marshall 1960A (Celestion G12-30)"
rename_file "$D" "+4x12 Green 20W" "4x12 Marshall 1960A (Celestion G12M20 Greenback)"
rename_file "$D" "+4x12 Green 25W" "4x12 Marshall 1960B (Celestion G12M25 Greenback)"
rename_file "$D" "+8x10 Blue Line" "8x10 Ampeg SVT"

# --- 3. PROCESSING: Revalver Amp ---
echo "Processing folder: Revalver Amp..."
D="Revalver Amp"
rename_file "$D" "+03 Herr Demon Ch1" "Diezel Herbert (Ch1)"
rename_file "$D" "+03 Herr Demon Ch2" "Diezel Herbert (Ch2)"
rename_file "$D" "+03 Herr Demon Ch3" "Diezel Herbert (Ch3)"
rename_file "$D" "+05 Peavey 6505 Clean" "Peavey 6505 (Clean)"
rename_file "$D" "+05 Peavey 6505 Crunch" "Peavey 6505 (Crunch)"
rename_file "$D" "+05 Peavey 6505 Lead" "Peavey 6505 (Lead)"
rename_file "$D" "+11 Angel PB II Clean" "ENGL Powerball II (Clean Channel)"
rename_file "$D" "+11 Angel PB II Crunch" "ENGL Powerball II (Crunch Channel)"
rename_file "$D" "+11 Angel PB II Hi-Lead" "ENGL Powerball II (Hi-Lead Channel)"
rename_file "$D" "+11 Angel PB II Lo-Lead" "ENGL Powerball II (Lo-Lead Channel)"
rename_file "$D" "+62 BluesMaker" "Marshall Bluesbreaker"
rename_file "$D" "+64 Fox AC30" "Vox AC30"
rename_file "$D" "+99 Peavey Classic 30 Ch1" "Peavey Classic 30 (Ch1)"
rename_file "$D" "+99 Peavey Classic 30 Ch2" "Peavey Classic 30 (Ch2)"

# --- 4. PROCESSING: Revalver Cab ---
echo "Processing folder: Revalver Cab..."
D="Revalver Cab"
rename_file "$D" "+Angel 412 Slant" "4x12 Angel 4x12 Slant"
rename_file "$D" "+Budda 412" "4x12 Budda 4x12"
rename_file "$D" "+Peavey 6505 412" "4x12 Peavey 6505 4x12"
rename_file "$D" "+Randy 412" "4x12 Randall 4x12"
rename_file "$D" "+Redhot PPC 412" "4x12 Orange PPC 4x12"

echo "--- Operation completed! ---"